services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./app/app.py:/app/app.py
      - ./templates:/app/templates
    depends_on:
      model-server:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
    tty: true

  model-server:
    build:
      context: .
      dockerfile: model_server/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./model_server/model_server.py:/app/model_server.py
      - ./src/model.py:/app/model.py
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f -X POST http://localhost:8001/infer -d 'text=test' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s
    tty: true