version: '3.8'

services:
  model-server:
    build:
      context: .
      dockerfile: model_server/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./model_server/model_server.py:/app/model_server.py
      - ./model_server/model.py:/app/model.py
    environment:
      - PYTHONUNBUFFERED=1
    tty: true

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./app/app.py:/app/app.py
      - ./templates:/app/templates
    depends_on:
      - model-server
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_SERVER_URL=http://model-server:8001/infer
    tty: true