version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - model-server
    environment:
      - PYTHONUNBUFFERED=1

  model-server:
    build:
      context: ./model_server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    expose:
      - "8001"
    environment:
      - PYTHONUNBUFFERED=1